### ISSUE TITLE
run 'npm install .' error

### ISSUE THREAD

**Issue by tacy** [kpdecker/monaco-yaml#1]
node version: v9.4.0
errmsg: 
```
Error: Error: ENOENT: no such file or directory, open '/home/tacy/workspace/react/monaco-yaml/node_modules/vscode-languageserver-types/lib/main.js'
In module tree:
    vs/languages/yaml/monaco.contribution
      vs/languages/yaml/yamlMode
        vs/languages/yaml/languageFeatures

    at Object.fs.openSync (fs.js:663:18)

    at /home/tacy/workspace/react/monaco-yaml/node_modules/requirejs/bin/r.js:23960:19
    at /home/tacy/workspace/react/monaco-yaml/node_modules/requirejs/bin/r.js:2896:39
    at /home/tacy/workspace/react/monaco-yaml/node_modules/requirejs/bin/r.js:2836:25
    at Function.prim.nextTick (/home/tacy/workspace/react/monaco-yaml/node_modules/requirejs/bin/r.js:23794:9)
    at Object.errback (/home/tacy/workspace/react/monaco-yaml/node_modules/requirejs/bin/r.js:2835:26)
    at Object.callback (/home/tacy/workspace/react/monaco-yaml/node_modules/requirejs/bin/r.js:2821:23)
    at Object.then (/home/tacy/workspace/react/monaco-yaml/node_modules/requirejs/bin/r.js:2875:23)
    at build (/home/tacy/workspace/react/monaco-yaml/node_modules/requirejs/bin/r.js:23919:12)
    at runBuild (/home/tacy/workspace/react/monaco-yaml/node_modules/requirejs/bin/r.js:25622:17)
    at Object.execCb (/home/tacy/workspace/react/monaco-yaml/node_modules/requirejs/bin/r.js:1869:33)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! monaco-yaml@1.0.0 prepublish: `gulp release`
npm ERR! Exit status 1
npm ERR!
```

**Comment by lujjjh** [comment]
The same error to me. 

It is because the lack of `package-lock.json`. I used `yarn` instead and the error was gone.

**Comment by tacy** [comment]
Solved my problem,  @lujjjh  thx

**Comment by tacy** [comment]
@lujjjh  Could you run this test right? It return a blank box  with can't edit

**Comment by lujjjh** [comment]
@tacy I have made some modifications to make the test work. I have no idea how @kpdecker could run the test successfully and wonder if a pull request is needed to fix the test.

```diff
diff --git a/test/index.html b/test/index.html
index 9abd2d9..e5b01bd 100644
--- a/test/index.html
+++ b/test/index.html
@@ -15,7 +15,7 @@
 	var require = {
 		paths: {
 			'vs/basic-languages': '../node_modules/monaco-languages/release',
-			'vs/language/yaml': '../release/dev',
+			'vs/languages/yaml': '../release/dev',
 			'vs': '../node_modules/monaco-editor-core/dev/vs'
 		}
 	};
@@ -27,78 +27,37 @@
 <script>
 	require([
 		'vs/basic-languages/src/monaco.contribution',
-		'vs/language/yaml/monaco.contribution'
+		'vs/languages/yaml/monaco.contribution'
 	], function() {
+		monaco.languages.yaml.yamlDefaults.setDiagnosticsOptions({
+			validate: true,
+			schemas: [{
+				fileMatch: ['*'],
+				schema: {
+					"title": "Person",
+					"type": "object",
+					"properties": {
+						"firstName": {
+							"type": "string"
+						},
+						"lastName": {
+							"type": "string"
+						},
+						"age": {
+							"description": "Age in years",
+							"type": "integer",
+							"minimum": 0
+						}
+					},
+					"required": ["firstName", "lastName"]
+				}
+			}]
+		});
+
 		var editor = monaco.editor.create(document.getElementById('container'), {
 			value: [
-				'{',
-				'	"type": "team",',
-				'	"test": {',
-				'		"testPage": "tools/testing/run-tests.htm",',
-				'		"enabled": true',
-				'	},',
-				'	"search": {',
-				'		"excludeFolders": [',
-				'			".git",',
-				'			"node_modules",',
-				'			"tools/bin",',
-				'			"tools/counts",',
-				'			"tools/policheck",',
-				'			"tools/tfs_build_extensions",',
-				'			"tools/testing/jscoverage",',
-				'			"tools/testing/qunit",',
-				'			"tools/testing/chutzpah",',
-				'			"server.net"',
-				'		]',
-				'	},',
-				'	"languages": {',
-				'		"vs.languages.typescript": {',
-				'			"validationSettings": [{',
-				'				"scope":"/",',
-				'				"noImplicitAny":true,',
-				'				"noLib":false,',
-				'				"extraLibs":[],',
-				'				"semanticValidation":true,',
-				'				"syntaxValidation":true,',
-				'				"codeGenTarget":"ES5",',
-				'				"moduleGenTarget":"",',
-				'				"lint": {',
-				'					"emptyBlocksWithoutComment": "warning",',
-				'					"curlyBracketsMustNotBeOmitted": "warning",',
-				'					"comparisonOperatorsNotStrict": "warning",',
-				'					"missingSemicolon": "warning",',
-				'					"unknownTypeOfResults": "warning",',
-				'					"semicolonsInsteadOfBlocks": "warning",',
-				'					"functionsInsideLoops": "warning",',
-				'					"functionsWithoutReturnType": "warning",',
-				'					"tripleSlashReferenceAlike": "warning",',
-				'					"unusedImports": "warning",',
-				'					"unusedVariables": "warning",',
-				'					"unusedFunctions": "warning",',
-				'					"unusedMembers": "warning"',
-				'				}',
-				'			},',
-				'			{',
-				'				"scope":"/client",',
-				'				"baseUrl":"/client",',
-				'				"moduleGenTarget":"amd"',
-				'			},',
-				'			{',
-				'				"scope":"/server",',
-				'				"moduleGenTarget":"commonjs"',
-				'			},',
-				'			{',
-				'				"scope":"/build",',
-				'				"moduleGenTarget":"commonjs"',
-				'			},',
-				'			{',
-				'				"scope":"/node_modules/nake",',
-				'				"moduleGenTarget":"commonjs"',
-				'			}],',
-				'			"allowMultipleWorkers": true',
-				'		}',
-				'	}',
-				'}',
+				'firstName: Bob',
+				'lastName: 10'
 			].join('\n'),
 			language: 'yaml'
 		});
```

**Comment by tacy** [comment]
Awesome, it work,  thx @lujjjh , you really saved my life. I think this is a good PR  :+1:

**Comment by kpdecker** [comment]
I did not update the tests when porting from the original code as I was testing in app. Would LOVE a PR for standalone tests!

**Comment by lujjjh** [comment]
@kpdecker @tacy I have created a pull request. Would you please check if it fixes this issue?

**Comment by tacy** [comment]
@lujjjh I am sure, pass my test :+1:

**Comment by kpdecker** [comment]
I'm sorry this took so long, but it's merged
